### ISSUE TITLE
Cardholder name not reported to Adyen when using Apply Pay with credit card

### ISSUE THREAD

**Issue by brain-effect** [Adyen/adyen-magento2-express-checkout#111]
**Is your feature request related to a problem? Please describe.**
Adyen fraud detection algorithms and VISA require cardholder name to be provided whenever a cc payment is done.

**Describe the solution you'd like**
I would like the cardholder name to be transferred to Adyen when doing an Apple Pay express payment with a credit card. 

**Describe alternatives you've considered**
None

**Additional context**

![Screenshot 2024-09-17 at 4 03 05 PM](https://github.com/user-attachments/assets/a9c455c0-ac6b-418b-8dba-0129d965ba5f)

**Comment by candemiralp** [comment]
Hello @brain-effect,

Thank you for reaching out and creating this issue. I will get back to you after a quick investigation.

Best Regards,
Can

**Comment by candemiralp** [comment]
Hello @brain-effect,

It looks like getting the card holder name is not possible. [EVMCo](https://www.emvco.com/) doesn't request the card holder name to be present while tokenising the card for Apple Pay wallets. This is a blocker on Apple Pay's side rather than Adyen's.

You can refer to [this thread](https://forums.developer.apple.com/forums/thread/715893) on Apple Pay forums.

Best regards,
Can
